[project]
name = "custom-models"
version = "0.1.0"
description = "Custom Implementation of Transfomer Models."
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "huggingface-hub>=0.34,<1",
    "matplotlib>=3.9",
    "numpy>=1.26",
    "requests>=2.32",
    "sentencepiece>=0.2.2",
    "tensorflow>=2.18,<3",
    "tiktoken>=0.7",
    "torch>=2.4,<3",
    "tqdm>=4.66",
    "ipywidgets>=8.1.9",
    "jupyterlab>=4.6.3",
    "transformers>=4.37,<5",
    "accelerate>=1.15.0",
    "bertviz>=1.4.1",
]

[[tool.uv.index]]
name = "microsoft"
url = "https://packagefeedproxy.microsoft.io/pypi/simple/"
default = true

[dependency-groups]
dev = [
    "build>=1.2.2.post1",
    "ipykernel>=7.3.0",
    "pytest>=8.3.5",
    "ruff>=0.4.4",
    "twine>=6.1.0",
]
